name: Automatic Upstream Fork Sync

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  sync:
    name: Sync Master Branch with Upstream
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync Fork
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh repo sync oneictag/CIPP-API -b master
